//! Shared registration plumbing for taku's Lua API crates.
//!
//! Every API crate exposes a backend trait, a `Local` impl, a `register`
//! function generated by [`lua_api!`], and an [`ApiEntry`] constant. The
//! runtime collects the entries into a single registry and installs each API
//! by calling its `register` with a [`RegisterCtx`].

use std::collections::HashMap;
use std::sync::Arc;

// Re-exported so `lua_api!` can name mlua types via `$crate::mlua` regardless
// of the expanding crate's dependencies.
pub use mlua;

/// Shared state handed to every API's registration hook. Constructed once per
/// Lua state by the runtime.
#[derive(Clone)]
pub struct RegisterCtx {
    pub dotenv: Arc<HashMap<String, String>>,
}

pub type RegisterFn = fn(&mlua::Lua, &RegisterCtx) -> mlua::Result<()>;

/// One registrable API: the Lua global it installs and how to install it.
#[derive(Clone, Copy)]
pub struct ApiEntry {
    pub global: &'static str,
    pub register: RegisterFn,
}

/// Generates a `fn $name(lua: &Lua, backend: Arc<dyn $trait>) -> mlua::Result<()>`
/// that builds the API's Lua table: one function per method, each closing over
/// its own clone of the backend, set as the `$global` global.
///
/// Grammar note: the closure's argument pattern is captured as a single token
/// tree, so it must be an identifier, `_`, or a parenthesized tuple; a method
/// taking no arguments is written `|_, (): ()| ...`.
#[macro_export]
macro_rules! lua_api {
    (
        $(#[$meta:meta])*
        $vis:vis fn $name:ident(global = $global:literal, backend: $trait:path as $b:ident) {
            $( $method:ident => |$lua:tt, $args:tt : $argty:ty| $body:expr ),+ $(,)?
        }
    ) => {
        $(#[$meta])*
        $vis fn $name(
            lua: &$crate::mlua::Lua,
            backend: ::std::sync::Arc<dyn $trait>,
        ) -> $crate::mlua::Result<()> {
            let tbl = lua.create_table()?;
            $({
                let $b = ::std::sync::Arc::clone(&backend);
                tbl.set(
                    stringify!($method),
                    lua.create_function(move |$lua, $args: $argty| $body)?,
                )?;
            })+
            lua.globals().set($global, tbl)?;
            Ok(())
        }
    };
}

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    trait Greeter: Send + Sync {
        fn greet(&self, name: &str) -> String;
        fn version(&self) -> u32;
    }

    struct Stub;

    impl Greeter for Stub {
        fn greet(&self, name: &str) -> String {
            format!("hello {name}")
        }
        fn version(&self) -> u32 {
            7
        }
    }

    crate::lua_api! {
        fn register(global = "greeter", backend: Greeter as g) {
            greet => |lua, (name, punct): (String, Option<String>)| {
                lua.create_string(g.greet(&name) + punct.as_deref().unwrap_or(""))
            },
            version => |_, (): ()| Ok(g.version()),
        }
    }

    #[test]
    fn generated_register_builds_the_global_and_dispatches() {
        let lua = mlua::Lua::new();
        register(&lua, Arc::new(Stub)).unwrap();
        lua.load(
            r#"
            assert(greeter.greet("taku", "!") == "hello taku!")
            assert(greeter.greet("taku") == "hello taku")
            assert(greeter.version() == 7)
        "#,
        )
        .exec()
        .unwrap();
    }
}
